modLoader="javafml"
loaderVersion="[38,)"
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId="moonlib"
version="${file.jarVersion}"
displayName="MoonLib"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="multiloader.png"
#credits=""
authors="HypherionSA"
description='A library mod used by HypherionSA\'s mods'

[[dependencies.moonlib]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.moonlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
